"""Phase 1: Initial schema

Revision ID: 7c19eba1f634
Revises: 
Create Date: 2025-11-09 03:24:48.328643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c19eba1f634'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parsed_resumes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_profile_id', sa.String(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('skills', sa.JSON(), nullable=False),
    sa.Column('achievements', sa.JSON(), nullable=True),
    sa.Column('work_history', sa.JSON(), nullable=False),
    sa.Column('education', sa.JSON(), nullable=True),
    sa.Column('companies', sa.JSON(), nullable=False),
    sa.Column('keywords', sa.JSON(), nullable=False),
    sa.Column('parsing_confidence', sa.Float(), nullable=False),
    sa.Column('parsed_at', sa.DateTime(), nullable=False),
    sa.Column('parser_version', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_profile_id'], ['user_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parsed_resumes_user_profile_id'), 'parsed_resumes', ['user_profile_id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('resume_file_path', sa.String(), nullable=True),
    sa.Column('resume_file_name', sa.String(), nullable=True),
    sa.Column('resume_file_size', sa.Integer(), nullable=True),
    sa.Column('resume_upload_date', sa.DateTime(), nullable=True),
    sa.Column('parsed_resume_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parsed_resume_id'], ['parsed_resumes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profiles_email'), 'user_profiles', ['email'], unique=True)
    op.create_index(op.f('ix_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=True)
    op.create_table('ally_types',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_profile_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('keywords', sa.JSON(), nullable=False),
    sa.Column('criteria', sa.Text(), nullable=True),
    sa.Column('search_parameters', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_profile_id'], ['user_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ally_types_user_profile_id'), 'ally_types', ['user_profile_id'], unique=False)
    op.create_table('dream_job_descriptions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('desired_role', sa.String(), nullable=True),
    sa.Column('desired_industry', sa.String(), nullable=True),
    sa.Column('desired_company_type', sa.String(), nullable=True),
    sa.Column('required_skills', sa.JSON(), nullable=True),
    sa.Column('responsibilities', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('previous_version_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['previous_version_id'], ['dream_job_descriptions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dream_job_descriptions_user_id'), 'dream_job_descriptions', ['user_id'], unique=False)
    op.create_table('deduced_ally_types',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('dream_job_id', sa.String(), nullable=False),
    sa.Column('ally_type_name', sa.String(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('selection_rationale', sa.Text(), nullable=False),
    sa.Column('search_queries', sa.JSON(), nullable=False),
    sa.Column('engagement_strategy', sa.Text(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('llm_model', sa.String(), nullable=False),
    sa.Column('llm_prompt_version', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['dream_job_id'], ['dream_job_descriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deduced_ally_types_dream_job_id'), 'deduced_ally_types', ['dream_job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deduced_ally_types_dream_job_id'), table_name='deduced_ally_types')
    op.drop_table('deduced_ally_types')
    op.drop_index(op.f('ix_dream_job_descriptions_user_id'), table_name='dream_job_descriptions')
    op.drop_table('dream_job_descriptions')
    op.drop_index(op.f('ix_ally_types_user_profile_id'), table_name='ally_types')
    op.drop_table('ally_types')
    op.drop_index(op.f('ix_user_profiles_user_id'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_email'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_parsed_resumes_user_profile_id'), table_name='parsed_resumes')
    op.drop_table('parsed_resumes')
    # ### end Alembic commands ###
