"""Phase 2: Add Contact, Content, SearchQuery, and SearchResult tables

Revision ID: 770917b594d2
Revises: 7c19eba1f634
Create Date: 2025-11-09 06:11:09.458532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '770917b594d2'
down_revision: Union[str, None] = '7c19eba1f634'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_queries',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('user_profile_id', sa.UUID(), nullable=False),
                    sa.Column('original_query', sa.String(
                        length=500), nullable=False),
                    sa.Column('ally_type_filters', postgresql.JSONB(astext_type=Text()),
                              nullable=True, comment='List of ally type UUIDs to filter search'),
                    sa.Column('counter_queries', postgresql.JSONB(astext_type=Text(
                    )), nullable=True, comment='Generated counter-queries for diverse perspectives'),
                    sa.Column('results_count', sa.Integer(), nullable=True),
                    sa.Column('status', sa.String(length=50), nullable=True,
                              comment='Status: processing, completed, failed'),
                    sa.Column('query_metadata', postgresql.JSONB(astext_type=Text()), nullable=True,
                              comment='Search parameters, platform filters, alternative_strategies, etc.'),
                    sa.Column('executed_at', sa.DateTime(), nullable=False),
                    sa.Column('completed_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['user_profile_id'], [
                        'user_profiles.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_search_queries_status'),
                    'search_queries', ['status'], unique=False)
    op.create_index(op.f('ix_search_queries_user_profile_id'),
                    'search_queries', ['user_profile_id'], unique=False)
    op.create_table('contacts',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('ally_type_id', sa.UUID(), nullable=True),
                    sa.Column('name', sa.String(length=255), nullable=False),
                    sa.Column('title', sa.String(length=255), nullable=True),
                    sa.Column('company', sa.String(length=255), nullable=True),
                    sa.Column('location', sa.String(
                        length=255), nullable=True),
                    sa.Column('email', sa.String(length=255), nullable=True),
                    sa.Column('phone', sa.String(length=50), nullable=True),
                    sa.Column('github_url', sa.String(
                        length=500), nullable=True),
                    sa.Column('twitter_url', sa.String(
                        length=500), nullable=True),
                    sa.Column('linkedin_url', sa.String(
                        length=500), nullable=True),
                    sa.Column('relevance_score', sa.Float(), nullable=True),
                    sa.Column('matched_keywords', postgresql.JSONB(
                        astext_type=Text()), nullable=True),
                    sa.Column('source_platform', sa.String(length=50), nullable=False,
                              comment='Platform: github, twitter, linkedin, apollo, manual'),
                    sa.Column('profile_data', postgresql.JSONB(astext_type=Text()),
                              nullable=True, comment='Full profile data from source platform'),
                    sa.Column('enrichment_data', postgresql.JSONB(astext_type=Text(
                    )), nullable=True, comment='Enrichment data from Apollo or other services'),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('last_updated', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['ally_type_id'], ['ally_types.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_contacts_ally_type_id'),
                    'contacts', ['ally_type_id'], unique=False)
    op.create_index(op.f('ix_contacts_company'),
                    'contacts', ['company'], unique=False)
    op.create_index(op.f('ix_contacts_email'),
                    'contacts', ['email'], unique=False)
    op.create_index(op.f('ix_contacts_name'),
                    'contacts', ['name'], unique=False)
    op.create_index(op.f('ix_contacts_relevance_score'),
                    'contacts', ['relevance_score'], unique=False)
    op.create_index(op.f('ix_contacts_source_platform'),
                    'contacts', ['source_platform'], unique=False)
    op.create_table('content',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('contact_id', sa.UUID(), nullable=False),
                    sa.Column('text', sa.Text(), nullable=False),
                    sa.Column('source_platform', sa.String(length=50), nullable=False,
                              comment='Platform: github, twitter, linkedin, blog, etc.'),
                    sa.Column('url', sa.String(length=500), nullable=True),
                    sa.Column('content_metadata', postgresql.JSONB(astext_type=Text()), nullable=True,
                              comment='Additional metadata (likes, shares, comments, tags, etc.)'),
                    sa.Column('posted_at', sa.DateTime(), nullable=True),
                    sa.Column('embedding_vector', sa.LargeBinary(), nullable=True,
                              comment='384-dim vector embedding from sentence-transformers'),
                    sa.Column('ally_type_classification', postgresql.JSONB(astext_type=Text(
                    )), nullable=True, comment='Relevance scores for each ally type {ally_type_id: score}'),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['contact_id'], ['contacts.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_content_contact_id'),
                    'content', ['contact_id'], unique=False)
    op.create_index(op.f('ix_content_posted_at'),
                    'content', ['posted_at'], unique=False)
    op.create_index(op.f('ix_content_source_platform'),
                    'content', ['source_platform'], unique=False)
    op.create_table('search_results',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('search_query_id', sa.UUID(), nullable=False),
                    sa.Column('contact_id', sa.UUID(), nullable=False),
                    sa.Column('match_score', sa.Float(), nullable=True),
                    sa.Column('matched_via', sa.String(length=100), nullable=True,
                              comment='original_query, counter_query, or specific counter_query text'),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['contact_id'], ['contacts.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['search_query_id'], [
                        'search_queries.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_search_results_contact_id'),
                    'search_results', ['contact_id'], unique=False)
    op.create_index(op.f('ix_search_results_search_query_id'),
                    'search_results', ['search_query_id'], unique=False)
    op.drop_constraint(None, 'user_profiles', type_='foreignkey')
    op.drop_column('user_profiles', 'parsed_resume_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column(
        'parsed_resume_id', sa.VARCHAR(), nullable=True))
    op.create_foreign_key(None, 'user_profiles', 'parsed_resumes', [
                          'parsed_resume_id'], ['id'])
    op.drop_index(op.f('ix_search_results_search_query_id'),
                  table_name='search_results')
    op.drop_index(op.f('ix_search_results_contact_id'),
                  table_name='search_results')
    op.drop_table('search_results')
    op.drop_index(op.f('ix_content_source_platform'), table_name='content')
    op.drop_index(op.f('ix_content_posted_at'), table_name='content')
    op.drop_index(op.f('ix_content_contact_id'), table_name='content')
    op.drop_table('content')
    op.drop_index(op.f('ix_contacts_source_platform'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_relevance_score'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_name'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_email'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_company'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_ally_type_id'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_search_queries_user_profile_id'),
                  table_name='search_queries')
    op.drop_index(op.f('ix_search_queries_status'),
                  table_name='search_queries')
    op.drop_table('search_queries')
    # ### end Alembic commands ###
